//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SLIT_H_
#define _SLIT_H_

#include <TinyCLR_Interop.h>
struct Library_SLIT_MFConsoleApplication1_Program
{
    static const int FIELD_STATIC__redLed = 0;
    static const int FIELD_STATIC__yellowLed = 1;
    static const int FIELD_STATIC__greenLed = 2;
    static const int FIELD_STATIC__pressRuttonUpInterrupt = 3;
    static const int FIELD_STATIC__pressRedButtonDownInterrupt = 4;
    static const int FIELD_STATIC__pressBlackButtonInterrupt = 5;
    static const int FIELD_STATIC__leds = 6;
    static const int FIELD_STATIC__number = 7;
    static const int FIELD_STATIC__lastInterrupt = 8;


    //--//

};

struct Library_SLIT_MFConsoleApplication1_Resources
{
    static const int FIELD_STATIC__manager = 9;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SLIT;

#endif  //_SLIT_H_
